Repository nicordev/formation-oc-php-projet5-blog, pull requests merged in 2019-02, with the labels that each got.

#28 Refactor manager: add methods to add, edit, delete, get and getAll directly in the Manager class
  src/Application.php
  src/Controller/BlogController.php
  src/Model/Entity/Comment.php
  src/Model/Entity/Entity.php
  src/Model/Entity/Post.php
  src/Model/Manager/CategoryManager.php
  src/Model/Manager/CommentManager.php
  src/Model/Manager/Manager.php
  src/Model/Manager/PostManager.php
  src/Model/Manager/TagManager.php
Labels: m

#34 Home: add a homepage
  public/css/style.css
  src/Controller/BlogController.php
  src/Controller/Controller.php
  src/Controller/HomeController.php
  src/view/home/home.twig
  src/view/home/postDeck.twig
Labels: enhancement, s

#32 Tag management: add a tag management system
  .gitignore
  public/css/style.css
  public/js/adminTagManager.js
  public/js/erase.js
  public/js/refreshValue.js
  public/js/tagManager.js
  src/Application.php
  src/Controller/BlogController.php
  src/Controller/ErrorController.php
  src/Controller/HomeController.php
  src/DIC.php
  src/Model/Entity/Post.php
  src/Model/Manager/Manager.php
  src/Model/Manager/PostManager.php
  src/Model/Manager/TagManager.php
  src/Router/Router.php
  src/view/blog/blogAdmin.twig
  src/view/blog/blogPost.twig
  src/view/blog/postEditor.twig
  src/view/home/home.twig
  src/view/layout.twig
Labels: enhancement, m

#35 Category management: add categories to regroup tags
  other/database/p5_create_tables.sql
  other/database/p5_demo.sql
  other/database/p5_mpd.png
  public/css/style.css
  public/js/adminTagManager.js
  public/js/application.js
  public/js/blogAdmin.js
  public/js/erase.js
  public/js/refreshValue.js
  public/js/tagHandler.js
  src/Controller/BlogController.php
  src/Controller/HomeController.php
  src/Model/Entity/Category.php
  src/Model/Manager/CategoryManager.php
  src/Model/Manager/Manager.php
  src/Model/Manager/PostManager.php
  src/Model/Manager/TagManager.php
  src/Router/Router.php
  src/view/blog/adminFooter.twig
  src/view/blog/blog.twig
  src/view/blog/blogAdmin.twig
  src/view/blog/blogPost.twig
  src/view/blog/categoryEditor.twig
  src/view/blog/message.twig
  src/view/blog/postEditor.twig
  src/view/blog/tagHandler.twig
  src/view/home/home.twig
  src/view/home/postDeck.twig
  src/view/layout.twig
  src/view/pageNotFound.twig
Labels: enhancement, l

#37 Blog theme: add a bootstrap theme to the website
  .gitignore
  public/css/admin-style.css
  public/css/clean-blog.css
  public/css/clean-blog.min.css
  public/css/old-style.css
  public/css/style.css
  public/img/about-bg.jpg
  public/img/contact-bg.jpg
  public/img/home-bg.jpg
  public/img/post-bg.jpg
  public/img/post-sample-image.jpg
  public/js/application.js
  public/js/blogAdmin.js
  public/js/clean-blog.js
  public/js/clean-blog.min.js
  src/view/blog/admin.twig
  src/view/blog/adminFooter.twig
  src/view/blog/blog.twig
  src/view/blog/blogAdmin.twig
  src/view/blog/blogPost.twig
  src/view/blog/categoryEditor.twig
  src/view/blog/message.twig
  src/view/blog/postEditor.twig
  src/view/blog/tagHandler.twig
  src/view/home/home.twig
  src/view/home/postDeck.twig
  src/view/layout.twig
Labels: enhancement, s

#38 Text editor: add a text editor to write blog posts
  src/Controller/BlogController.php
  src/view/blog/blogPost.twig
  src/view/blog/postEditor.twig
Labels: enhancement, s

#39 Tag page: add a page to show all posts of a tag
  other/query.sql
  public/css/style.css
  public/index.php
  src/Controller/BlogController.php
  src/Model/Entity/Post.php
  src/Model/Manager/CategoryManager.php
  src/Model/Manager/PostManager.php
  src/Router/Router.php
  src/view/blog/blogAdmin.twig
  src/view/blog/blogPost.twig
  src/view/blog/blogpostClassification.twig
  src/view/blog/tagPage.twig
Labels: enhancement, s

#40 Refactor admin: make some changes before creating the member system
  other/query.sql
  public/css/admin-style.css
  public/css/style.css
  public/js/application.js
  public/js/blogAdmin.js
  public/js/tagHandler.js
  src/Controller/BlogController.php
  src/Controller/Controller.php
  src/Model/Manager/CategoryManager.php
  src/Model/Manager/Manager.php
  src/Model/Manager/PostManager.php
  src/Model/Manager/TagManager.php
  src/Router/Router.php
  src/view/admin/admin.twig
  src/view/admin/blogAdmin.twig
  src/view/admin/categoryEditor.twig
  src/view/admin/postEditor.twig
  src/view/admin/tagHandler.twig
  src/view/blog/blogPost.twig
  src/view/blog/message.twig
  src/view/message.twig
Labels: s
